#layout=bottombar # default
#seekbarstyle=bar
scalewindowed=1.5
scalefullscreen=1.5

# keeps same osc size eg between 300x600 or 600x300 window sizes
vidscale=no

# area around osc to show osc on mouse move (0: everywhere, 1: mouse hover osc only)
deadzonesize=0

# Change button to open menu on left click
# See man mpv
# playlist_next_mbtn_left_command=script-binding select/select-playlist; script-message-to osc osc-hide
# title_mbtn_left_command=script-binding select/select-watch-history; script-message-to osc osc-hide
# chapter_prev_mbtn_left_command=script-binding select/select-chapter; script-message-to osc osc-hide
# chapter_next_mbtn_left_command=script-binding select/select-chapter; script-message-to osc osc-hide
audio_track_mbtn_left_command=script-binding select/select-aid; script-message-to osc osc-hide
sub_track_mbtn_left_command=script-binding select/select-sid; script-message-to osc osc-hide
# volume_mbtn_left_command=script-binding select/select-audio-device; script-message-to osc osc-hide

# Add custom button for video selection
custom_button_1_content=🎞
custom_button_1_mbtn_left_command=script-binding select/select-vid; script-message-to osc osc-hide
