#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"
here="$(pwd)"

wallpapers_list_file="wallpapers.list"
dst_blured="wallpaper.blured.png"
blured_ext=".blured.png"

mapfile -t wallpapers_list < "$wallpapers_list_file"

wallpaperc="${#wallpapers_list[@]}"
wallpaper="${wallpapers_list[RANDOM % wallpaperc]}"

/usr/bin/feh --bg-fill "$wallpaper"
ln -sf "$wallpaper$blured_ext" "$dst_blured"
