#!/bin/bash




function mymerge() {
	if [ ! -e "$1" ]
	then
		echo "## not such file or dir: $1"
		return
	fi
	if [ ! -e "$2" ]
	then
		echo "## not such file or dir: $2"
		return
	fi

	MERGER="meld"
	if [ "$OS" = "Windows_NT" ]
	then
		echo "You are on Windows"
		MERGER="/c/Program Files (x86)/Meld/meld/meld.exe"
	fi

    if [ -n "$(diff $1 $2)" ]
    then
        echo "$> $MERGER $1 $2"
        "$MERGER" $1 $2 # &> /dev/null
    else
        echo "## ( no diff: $1 $2 )"
    fi
}

mymerge oh-my-zsh-install.sh ~/.oh-my-zsh/tools/install.sh
mymerge ~/bin bin
mymerge ~/.conky .conky
mymerge ~/.dzen .dzen
mymerge ~/.emacs .emacs
mymerge ~/.emacs.d .emacs.d
mymerge ~/.gitconfig .gitconfig
mymerge ~/.gitconfig.win .gitconfig.win
mymerge ~/.gitignore .gitignore
mymerge ~/.i3 .i3
mymerge ~/.ncmpcpp .ncmpcpp
mymerge ~/.oh-my-zsh/custom .oh-my-zsh/custom
mymerge ~/oh-my-zsh-install.sh oh-my-zsh-install.sh
mymerge ~/.screenrc .screenrc
mymerge ~/scripts scripts
mymerge ~/.userscripts .userscripts
mymerge ~/.Xdefaults .Xdefaults
mymerge ~/.xinitrc .xinitrc
mymerge ~/.zshrc .zshrc
