#!/bin/zsh

function mymerge() {
    if [ -n "$(diff $1 $2)" ]
    then
        echo ">> merge $1 $2"
        meld $1 $2 &> /dev/null
    else
        echo ">> ( no diff: $1 $2 )"
    fi
}

mymerge oh-my-zsh-install.sh ~/.oh-my-zsh/tools/install.sh
mymerge ~/bin bin
mymerge ~/.conky .conky
mymerge ~/.dzen .dzen
mymerge ~/.emacs .emacs
mymerge ~/.emacs.d .emacs.d
mymerge ~/.gitconfig .gitconfig
mymerge ~/.gitconfig.win .gitconfig.win
mymerge ~/.gitignore .gitignore
mymerge ~/.i3 .i3
mymerge ~/.ncmpcpp .ncmpcpp
mymerge ~/.oh-my-zsh .oh-my-zsh
mymerge ~/oh-my-zsh-install.sh oh-my-zsh-install.sh
mymerge ~/.screenrc .screenrc
mymerge ~/scripts scripts
mymerge ~/.userscripts userscripts
mymerge ~/.Xdefaults .Xdefaults
mymerge ~/.xinitrc .xinitrc
mymerge ~/.zshrc .zshrc

mymerge / system
