context.modules = [
{   name = libpipewire-module-parametric-equalizer
    args = {
        # remote.name = "pipewire-0"
        equalizer.description = "EQ rtings HD6XX Rtings.com"
        equalizer.filepath = "/home/jo/.config/pipewire/eq/hd6xx/Target_Rtings_com_Consolidated/Sennheiser_HD6XX_Target_Rtings_com_ParametricEQ_10Band.txt"
        audio.channels = 2
        audio.position = [FL, FR]
        capture.props = {
         node.name      = "effect_input.eq_hd6xx_rtings_com"
         media.class = Audio/Sink
         filter.smart = true
         filter.smart.disabled = false
         # filter.smart.target = { node.name = "alsa_output....." }
        }
        playback.props = {
         node.name      = "effect_output.eq_hd6xx_rtings_com"
         node.passive = true
         # media.role = "DSP"
        }
    }
}
]
