#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/emacsd

case "$1" in
	start)
		$0 stop
		stat_busy 'Starting emacs daemons'
		for emacsd_name in "${EMACSD[@]}"
		do
			sudo -u $EMACSD_USER emacs "--daemon=$emacsd_name"
		done
		stat_done
		;;
	stop)
		kill -9 `pgrep -f "emacs --daemon"` &> /dev/null
		;;
	restart)
		$0 stop
		$0 start
esac

exit 0
